
daily_data = {
    "date": "2024-09-26",
    "tweets": [
            {
                "startTime": "01:02",
                "arxivId": "2409.17146",
                "arxivLink": "https://arxiv.org/abs/2409.17146",
                "title": "Open-Weight VLMs: No More Distilling, Just Describing!",
                "institute": "Allen Institute for AI, University of Washington",
                "text": "This research introduces a new family of vision-language models (VLMs) called Molmo, which are trained on a novel, high-quality image captioning dataset called PixMo. Unlike previous open-weight VLMs, Molmo does not rely on synthetic data generated by proprietary systems, making it truly open and reproducible.",
                "paper-title": "Molmo and PixMo: Open Weights and Open Data for State-of-the-Art Multimodal Models",
                "image-path": "flux_paper_image/2409.17146_1727388997.png"
            },

            {
                "startTime": "01:29",
                "arxivId": "2409.16427",
                "arxivLink": "https://arxiv.org/abs/2409.16427",
                "title": "AI Agents on Trial: A Sandbox for Testing Their Safety in the Real World",
                "institute": "Carnegie Mellon University, Allen Institute for AI, University of Washington...",
                "text": "This research introduces HAICOSYSTEM, a framework that simulates multi-turn interactions between AI agents and human users in a sandbox environment. Unlike previous work that focuses on single-turn interactions or isolated safety risks, HAICOSYSTEM examines the safety of AI agents across diverse scenarios and tool use, considering both benign and malicious user intents.",
                "paper-title": "HAICOSYSTEM: An Ecosystem for Sandboxing Safety Risks in Human-AI Interactions",
                "image-path": "flux_paper_image/2409.16427_1727389808.png"
            },

            {
                "startTime": "01:54",
                "arxivId": "2409.16517",
                "arxivLink": "https://arxiv.org/abs/2409.16517",
                "title": "LLMs: Charting a New Course for Multi-Modality Models",
                "institute": "Microsoft",
                "text": "This research focuses on building a large-scale chart dataset, SynChart, using LLMs to generate synthetic chart data, rather than relying on existing datasets or code-based approaches.",
                "paper-title": "SynChart: Synthesizing Charts from Language Models",
                "image-path": "flux_paper_image/2409.16517_1727389158.png"
            },

            {
                "startTime": "02:14",
                "arxivId": "2409.17095",
                "arxivLink": "https://arxiv.org/abs/2409.17095",
                "title": "Text Recognition: A New Way to Crack the Code!",
                "institute": "\u00c9cole des Ponts ParisTech",
                "text": "This research introduces a detection-based approach to text line recognition, which differs from the prevalent autoregressive decoding methods. Instead of predicting characters one by one, it detects all characters in parallel, treating the entire line as a single unit.",
                "paper-title": "General Detection-based Text Line Recognition",
                "image-path": "flux_paper_image/2409.17095_1727389862.png"
            },

            {
                "startTime": "02:44",
                "arxivId": "2409.16766",
                "arxivLink": "https://arxiv.org/abs/2409.16766",
                "title": "Lensless Cameras: Seeing Through the Noise of Everyday Light!",
                "institute": "\u00c9cole Polytechnique F\u00e9d\u00e9rale de Lausanne",
                "text": "This research focuses on the impact of external illumination on lensless imaging, a problem largely ignored in previous studies. It proposes techniques to address this issue by incorporating an estimate of the external illumination into the image recovery process.",
                "paper-title": "Let There Be Light: Robust Lensless Imaging Under External Illumination With Deep Learning",
                "image-path": "flux_paper_image/2409.16766_1727389795.png"
            },

            {
                "startTime": "03:07",
                "arxivId": "2409.16434",
                "arxivLink": "https://arxiv.org/abs/2409.16434",
                "title": "PETL: The Fine-Tuning Revolution That's Not So Fine After All?",
                "institute": "The Ohio State University, Google Research",
                "text": "This research conducts a unifying empirical study of parameter-efficient transfer learning (PETL) approaches for visual recognition, systematically comparing their performance and exploring their complementary nature. Unlike previous work, it goes beyond low-shot scenarios and investigates PETL's effectiveness in many-shot regimes, as well as its ability to preserve robustness to distribution shifts.",
                "paper-title": "Lessons Learned from a Unifying Empirical Study of Parameter-Efficient Transfer Learning (PETL) in Visual Recognition",
                "image-path": "flux_paper_image/2409.16434_1727389765.png"
            },

            {
                "startTime": "03:29",
                "arxivId": "2409.16560",
                "arxivLink": "https://arxiv.org/abs/2409.16560",
                "title": "LLMs Get a Speed Boost: Beam Decoding Goes Dynamic!",
                "institute": "University of California Los Angeles",
                "text": "This research introduces a novel method called \"dynamic-width speculative beam decoding\" (DSBD) that combines speculative decoding with beam sampling for faster and more accurate LLM inference. Unlike previous work that focused on single-sequence generation, DSBD leverages multiple candidate sequences, dynamically adjusting their number based on the context.",
                "paper-title": "Dynamic-Width Speculative Beam Decoding for Efficient LLM Inference",
                "image-path": "flux_paper_image/2409.16560_1727389047.png"
            },

            {
                "startTime": "03:59",
                "arxivId": "2409.16491",
                "arxivLink": "https://arxiv.org/abs/2409.16491",
                "title": "Deepfakes, Be Gone! New Research Turns Adversarial Attacks into Social Good.",
                "institute": "Michigan State University, Meta",
                "text": "This research explores \"proactive schemes\" for embedding templates into digital media, which are designed to enhance the performance of deep learning models and protect against adversarial attacks. This approach differs from previous work that focused on passive methods, which don't modify the input data distribution.",
                "paper-title": "Proactive Schemes: A Survey of Adversarial Attacks for Social Good",
                "image-path": "flux_paper_image/2409.16491_1727390145.png"
            },

            {
                "startTime": "04:20",
                "arxivId": "2409.16686",
                "arxivLink": "https://arxiv.org/abs/2409.16686",
                "title": "Embodied AI Gets a Memory Makeover: Multi-Scale Insights for Smarter Decisions",
                "institute": "Beijing University of Posts and Telecommunications, Tsinghua University",
                "text": "This research introduces MSI-Agent, an embodied agent that improves planning and decision-making by summarizing and utilizing insights at multiple scales. Unlike previous work that focused on single-scale insights, MSI-Agent leverages a three-part pipeline to generate task-specific insights, store them in a database, and then use relevant insights to aid in decision-making.",
                "paper-title": "MSI-Agent: Incorporating Multi-Scale Insight into Embodied Agents for Superior Planning and Decision-Making",
                "image-path": "flux_paper_image/2409.16686_1727390291.png"
            },

            {
                "startTime": "04:48",
                "arxivId": "2409.17126",
                "arxivLink": "https://arxiv.org/abs/2409.17126",
                "title": "From \"Giraffe\" to Giraffe: AI Designs & Robots Build It!",
                "institute": "UC Berkeley, Cornell University",
                "text": "This research introduces a new problem called Generative Design-for-Robot-Assembly (GDfRA). Unlike previous work that focuses on designing for assembly with human input, GDfRA aims to automate the entire design process using AI. Blox-Net, the system presented in the paper, combines a vision language model (VLM) with a physical robot and physics simulation to generate designs and assemble them autonomously.",
                "paper-title": "Blox-Net: Generative Design-for-Robot-Assembly Using VLM Supervision, Physics Simulation, and a Robot with Reset",
                "image-path": "flux_paper_image/2409.17126_1727390110.png"
            },

            {
                "startTime": "05:11",
                "arxivId": "2409.16663",
                "arxivLink": "https://arxiv.org/abs/2409.16663",
                "title": "Driving AI That Dreams: World Models for Smarter Cars",
                "institute": "NVIDIA",
                "text": "This research introduces a novel approach to address the covariate shift problem in imitation learning for autonomous vehicles by leveraging latent space generative world models. Unlike previous methods that rely on collecting additional data or using heuristics, this approach trains a driving policy to recover from errors by aligning with states observed in human demonstrations.",
                "paper-title": "Mitigating Covariate Shift in Imitation Learning for Autonomous Vehicles Using Latent Space Generative World Models",
                "image-path": "flux_paper_image/2409.16663_1727389085.png"
            },

            {
                "startTime": "05:32",
                "arxivId": "2409.16301",
                "arxivLink": "https://arxiv.org/abs/2409.16301",
                "title": "Deep Learning Gives Robots a Leg Up on Stability!",
                "institute": "Tsinghua University, UC Berkeley, University of Southern California",
                "text": "This research uses deep learning to estimate the \"region of attraction\" (RoA) for walking robots, which is the set of states from which the robot can stabilize to a desired gait. This approach differs from previous work by leveraging neural networks to approximate solutions to the Hamilton-Jacobi (HJ) partial differential equations (PDEs), overcoming the computational limitations of traditional numerical methods.",
                "paper-title": "Gait Switching and Enhanced Stabilization of Walking Robots with Deep Learning-based Reachability: A Case Study on Two-link Walker",
                "image-path": "flux_paper_image/2409.16301_1727388602.png"
            },

            {
                "startTime": "06:02",
                "arxivId": "2409.16499",
                "arxivLink": "https://arxiv.org/abs/2409.16499",
                "title": "Learning Linear Dynamics from Bilinear Observations: A New Twist on System Identification!",
                "institute": "Cornell University, MIT",
                "text": "This paper focuses on learning the dynamics of a system where the input affects both the state update and the observation of the state, a scenario not extensively studied before. It introduces a new approach to estimate the system's Markov parameters from bilinear observations.",
                "paper-title": "Learning Linear Dynamics from Bilinear Observations",
                "image-path": "flux_paper_image/2409.16499_1727389546.png"
            },

            {
                "startTime": "06:25",
                "arxivId": "2409.16572",
                "arxivLink": "https://arxiv.org/abs/2409.16572",
                "title": "Deep Learning Goes Underground: A Faster, Smarter Way to Store Carbon",
                "institute": "Yale University",
                "text": "This research introduces a new deep learning framework called \"nested Fourier-DeepONet\" for simulating geological carbon sequestration (GCS). This framework combines the strengths of two existing techniques, Fourier neural operators (FNO) and deep operator networks (DeepONet), to improve computational efficiency and generalization capabilities compared to previous FNO-based approaches.",
                "paper-title": "Efficient and generalizable nested Fourier-DeepONet for three-dimensional geological carbon sequestration",
                "image-path": "flux_paper_image/2409.16572_1727388646.png"
            },

            {
                "startTime": "06:46",
                "arxivId": "2409.16947",
                "arxivLink": "https://arxiv.org/abs/2409.16947",
                "title": "Stereo Image Super-Resolution: A Race to the Finish Line (Under 1MB!)",
                "institute": "LAVA, NTIRE, \u00c9cole Normale Sup\u00e9rieure...",
                "text": "This research introduces a new constraint on computational complexity, limiting the model size to 1MB and the number of MACs to 400G, making it more relevant for real-world applications on resource-limited devices.",
                "paper-title": "NTIRE 2024 Challenge on Stereo Image Super-Resolution: Methods and Results",
                "image-path": "flux_paper_image/2409.16947_1727390035.png"
            },

            {
                "startTime": "07:09",
                "arxivId": "2409.17005",
                "arxivLink": "https://arxiv.org/abs/2409.17005",
                "title": "Math Models: Not Just Symbols, But Conversations!",
                "institute": "University of Texas at Austin, MIT",
                "text": "This research argues that math models should consider the communicative aspects of human-generated math, going beyond purely symbolic representations. It suggests that language models can learn and represent the communicative intentions embedded in mathematical expressions.",
                "paper-title": "Models Can and Should Embrace the Communicative Nature of Human-Generated Math",
                "image-path": "flux_paper_image/2409.17005_1727389023.png"
            },

            {
                "startTime": "07:29",
                "arxivId": "2409.16997",
                "arxivLink": "https://arxiv.org/abs/2409.16997",
                "title": "INT8 Attention: Making LLMs Faster and Smaller with a Pinch of Quantization",
                "institute": "Peking University",
                "text": "This paper introduces INT-FlashAttention, a novel architecture that integrates INT8 quantization with FlashAttention, a technique for accelerating attention computation in large language models. Unlike previous work that focused on tensor-level quantization, INT-FlashAttention utilizes token-level quantization, which preserves more information and leads to higher accuracy.",
                "paper-title": "INT-FlashAttention: Enabling Flash Attention for INT8 Quantization",
                "image-path": "flux_paper_image/2409.16997_1727389177.png"
            },

            {
                "startTime": "07:55",
                "arxivId": "2409.16346",
                "arxivLink": "https://arxiv.org/abs/2409.16346",
                "title": "Quantum Compilation: Machine Learning Makes It a Breeze!",
                "institute": "ETH Zurich, Los Alamos National Laboratory, University of Toronto",
                "text": "This research explores a variational quantum compilation (VQC) scheme that leverages out-of-distribution generalization results from quantum machine learning (QML). Unlike previous VQC methods, this approach trains a parameterized quantum circuit (PQC) on a small dataset of product states, enabling it to generalize to highly entangled states.",
                "paper-title": "Scalable quantum dynamics compilation via quantum machine learning",
                "image-path": "flux_paper_image/2409.16346_1727389842.png"
            },

            {
                "startTime": "08:19",
                "arxivId": "2409.16618",
                "arxivLink": "https://arxiv.org/abs/2409.16618",
                "title": "Backdoor Attacks: Now They're Claiming Your Data!",
                "institute": "Korea Advanced Institute of Science and Technology",
                "text": "This research introduces a new type of backdoor attack that uses the inherent claims within a sentence as triggers, eliminating the need for input manipulation after model distribution. Unlike previous methods that rely on altering input queries, this approach leverages the model's understanding of claims to manipulate its decisions.",
                "paper-title": "Claim-Guided Textual Backdoor Attack for Practical Applications",
                "image-path": "flux_paper_image/2409.16618_1727390081.png"
            },

            {
                "startTime": "08:39",
                "arxivId": "2409.16603",
                "arxivLink": "https://arxiv.org/abs/2409.16603",
                "title": "AI Doctors: New Study Tests Robots' Ability to Write Discharge Summaries!",
                "institute": "Stanford University",
                "text": "This research introduces two new shared tasks, RRG24 and \"Discharge Me!\", focusing on the generation of radiology reports and discharge summaries, respectively. These tasks are distinct from previous work by using a larger, more diverse dataset and incorporating clinician review in the evaluation process.",
                "paper-title": "Overview of the First Shared Task on Clinical Text Generation: RRG24 and “Discharge Me!”",
                "image-path": "flux_paper_image/2409.16603_1727389784.png"
            },

            {
                "startTime": "08:57",
                "arxivId": "2409.16407",
                "arxivLink": "https://arxiv.org/abs/2409.16407",
                "title": "Stop the Weight-Loss! New Research Finds the Perfect Representation for Causal Inference",
                "institute": "University of Oxford, University of California Berkeley",
                "text": "This paper introduces a new method for finding design-based weights in causal inference. Unlike previous approaches that rely on specific assumptions about the data generating process, this method learns a representation of the covariates that minimizes the information lost when using a weighted estimator.",
                "paper-title": "Towards Representation Learning for Weighting Problems in Design-Based Causal Inference",
                "image-path": "flux_paper_image/2409.16407_1727389626.png"
            },

            {
                "startTime": "09:25",
                "arxivId": "2409.16546",
                "arxivLink": "https://arxiv.org/abs/2409.16546",
                "title": "KV-Cache Gets a Precision Makeover: Aligning Bits for Faster LLMs",
                "institute": "Tsinghua University",
                "text": "This research introduces a new criterion called \"precision alignment\" to quantitatively evaluate the importance of parameters in mixed-precision quantization. Unlike previous work that relied on qualitative analysis and manual experiments, this approach provides a systematic framework for determining the optimal bit-width for each parameter.",
                "paper-title": "AlignedKV: Reducing Memory Access of KV-Cache with Precision-Aligned Quantization",
                "image-path": "flux_paper_image/2409.16546_1727390326.png"
            },

            {
                "startTime": "09:47",
                "arxivId": "2409.16986",
                "arxivLink": "https://arxiv.org/abs/2409.16986",
                "title": "Data Selection for LLMs: Quality AND Diversity? Quad's Got Your Back!",
                "institute": "Beijing Institute of Technology, SenseTime, Purple Mountain Observatory...",
                "text": "This paper introduces Quad, a data selection approach for pre-training large language models (LLMs) that prioritizes both data quality and diversity. Unlike previous methods that focus solely on quality, Quad uses a multi-armed bandit (MAB) framework to balance the selection of high-influence data with the exploration of diverse data clusters.",
                "paper-title": "Harnessing Diversity for Important Data Selection in Pretraining Large Language Models",
                "image-path": "flux_paper_image/2409.16986_1727390023.png"
            },

            {
                "startTime": "10:18",
                "arxivId": "2409.16718",
                "arxivLink": "https://arxiv.org/abs/2409.16718",
                "title": "Fine-Tuning Vision-Language Models: A Tiny Tweak, A Big Boost!",
                "institute": "University of Tokyo, University of Southern California, Xiamen University",
                "text": "This research explores a parameter-efficient fine-tuning method for Vision-Language Models (VLMs) called CLIPFit. Unlike previous methods that introduce external parameters, CLIPFit focuses on fine-tuning specific inherent parameters within the VLM, specifically bias terms in the text encoder and LayerNorm in the image encoder.",
                "paper-title": "Vision-Language Model Fine-Tuning via Simple Parameter-Efficient Modification",
                "image-path": "flux_paper_image/2409.16718_1727389193.png"
            },

            {
                "startTime": "10:43",
                "arxivId": "2409.16541",
                "arxivLink": "https://arxiv.org/abs/2409.16541",
                "title": "Smoothing Out the Wrinkles: A New Way to Fit Data with Sobolev Budgets",
                "institute": "University of British Columbia, University of California Berkeley, Korea Advanced Institute of Science and Technology (KAIST)...",
                "text": "This paper introduces a new approach to approximating probability measures using a measure whose support is parametrized by a function. The key innovation is the use of a Sobolev norm as a constraint, which allows for the control of the complexity of the approximation by bounding the derivatives of the function. This differs from previous work that typically used length constraints or geometric constraints.",
                "paper-title": "Monge-Kantorovich Fitting With Sobolev Budgets",
                "image-path": "flux_paper_image/2409.16541_1727388718.png"
            },

            {
                "startTime": "11:07",
                "arxivId": "2409.16471",
                "arxivLink": "https://arxiv.org/abs/2409.16471",
                "title": "Neural ODEs: Score-Based Flow for Mean Field Control Problems",
                "institute": "UC Los Angeles, University of South Carolina",
                "text": "This paper proposes a system of neural ODEs representing first- and second-order score functions along trajectories, which is used to reformulate the mean field control (MFC) problem with individual noises into an unconstrained optimization problem. This approach differs from previous work by directly computing the score functions using neural ODEs, rather than relying on score-matching methods.",
                "paper-title": "Score-based Neural Ordinary Differential Equations for Computing Mean Field Control Problems",
                "image-path": "flux_paper_image/2409.16471_1727389238.png"
            },

            {
                "startTime": "11:29",
                "arxivId": "2409.16644",
                "arxivLink": "https://arxiv.org/abs/2409.16644",
                "title": "Speech Quality Evaluator: LLMs Get a Voice!",
                "institute": "Tsinghua University",
                "text": "This research explores using auditory large language models (LLMs) for speech quality assessment, a task typically handled by smaller, task-specific models. The paper demonstrates that finetuned auditory LLMs can predict MOS and SIM scores, perform A/B testing, and even generate natural language descriptions of speech quality.",
                "paper-title": "Enabling Auditory Large Language Models for Automatic Speech Quality Evaluation",
                "image-path": "flux_paper_image/2409.16644_1727390352.png"
            },

            {
                "startTime": "11:48",
                "arxivId": "2409.17113",
                "arxivLink": "https://arxiv.org/abs/2409.17113",
                "title": "LLMs Have Secret Zones: Where Tiny Tweaks Don't Matter (Much)",
                "institute": "LASR Labs, University of Oxford, Apollo Research",
                "text": "This paper identifies \"stable regions\" in the residual stream of Transformers, where small changes in activations have minimal impact on the model's output. This differs from previous work on polytopes, which are smaller and don't correspond to semantic distinctions.",
                "paper-title": "Characterizing stable regions in the residual stream of LLMs",
                "image-path": "flux_paper_image/2409.17113_1727388701.png"
            },

            {
                "startTime": "12:06",
                "arxivId": "2409.17140",
                "arxivLink": "https://arxiv.org/abs/2409.17140",
                "title": "Turning Apps into Agents: LLMs Make Software Super Smart!",
                "institute": "Peking University, Nanjing University, Microsoft",
                "text": "This research proposes a new framework called AXIS that prioritizes using application programming interfaces (APIs) over user interface (UI) interactions for LLM-based agents. This approach differs from previous work that focused on UI-based agents, which often suffer from high latency and low reliability due to the need for numerous sequential interactions.",
                "paper-title": "Turn Every Application into an Agent: Towards Efficient Human-Agent-Computer Interaction with API-First LLM-Based Agents",
                "image-path": "flux_paper_image/2409.17140_1727388916.png"
            },

            {
                "startTime": "12:30",
                "arxivId": "2409.16653",
                "arxivLink": "https://arxiv.org/abs/2409.16653",
                "title": "Transformers Get a Credibility Boost: New Model Predicts Insurance Claims Better Than Ever!",
                "institute": "Parthenope University of Naples, ETH Zurich",
                "text": "This research introduces a novel credibility mechanism to the Transformer architecture, which is typically used for time-series data. The authors apply this mechanism to tabular data, specifically for predicting insurance claims. This approach differs from previous work by incorporating a special token that encodes prior information and combines it with observation-based information in a credibility-weighted average.",
                "paper-title": "The Credibility Transformer",
                "image-path": "flux_paper_image/2409.16653_1727390257.png"
            },

            {
                "startTime": "12:56",
                "arxivId": "2409.16767",
                "arxivLink": "https://arxiv.org/abs/2409.16767",
                "title": "Neural Collapse: Entropy's Got a New Dance Move!",
                "institute": "University of Science and Technology Beijing, Tsinghua University",
                "text": "This research uses information-theoretic metrics like matrix entropy and mutual information to analyze Neural Collapse, a phenomenon observed during supervised learning. Unlike previous work that focused on similarity, this study explores the information interplay between data representations and classification head weights.",
                "paper-title": "Exploring Information-Theoretic Metrics Associated with Neural Collapse in Supervised Training",
                "image-path": "flux_paper_image/2409.16767_1727390297.png"
            },

            {
                "startTime": "13:20",
                "arxivId": "2409.16666",
                "arxivLink": "https://arxiv.org/abs/2409.16666",
                "title": "TalkinNeRF: Giving Digital Humans a Voice (and Hands!)",
                "institute": "Stony Brook University, Meta",
                "text": "This research introduces TalkinNeRF, a novel framework that learns a dynamic neural radiance field (NeRF) for full-body talking humans from monocular videos. Unlike previous work that focuses on either body pose or facial expressions, TalkinNeRF combines both, along with hand articulation, to create more realistic and expressive digital humans.",
                "paper-title": "TalkinNeRF: Animatable Neural Fields for Full-Body Talking Humans",
                "image-path": "flux_paper_image/2409.16666_1727389474.png"
            },

            {
                "startTime": "13:39",
                "arxivId": "2409.17066",
                "arxivLink": "https://arxiv.org/abs/2409.17066",
                "title": "LLMs Go on a Diet: Extreme Low-Bit Quantization for Language Models",
                "institute": "Microsoft, University of Science and Technology of China",
                "text": "This research introduces Vector Post-Training Quantization (VPTQ), a new method for compressing large language models (LLMs) to extremely low bit-widths. Unlike previous methods that quantize individual weights, VPTQ quantizes entire vectors of weights, which allows for greater compression and accuracy.",
                "paper-title": "VPTQ: Extreme Low-bit Vector Post-Training Quantization for Large Language Models",
                "image-path": "flux_paper_image/2409.17066_1727390340.png"
            },

            {
                "startTime": "14:04",
                "arxivId": "2409.17020",
                "arxivLink": "https://arxiv.org/abs/2409.17020",
                "title": "RIS on a Diet: How to Slim Down Image Segmentation Models Without Losing Brains",
                "institute": "Shanghai University of Engineering Science, SenseTime, Carnegie Mellon University",
                "text": "This paper focuses on post-training quantization (PTQ) for referring image segmentation (RIS) models, a task that involves understanding both images and text. Unlike previous PTQ methods designed for single-modal CNNs or transformers, this research proposes a tailored approach for RIS models, addressing the unique challenges of multi-modal data.",
                "paper-title": "PTQ4RIS: Post-Training Quantization for Referring Image Segmentation",
                "image-path": "flux_paper_image/2409.17020_1727389695.png"
            },

            {
                "startTime": "14:28",
                "arxivId": "2409.16722",
                "arxivLink": "https://arxiv.org/abs/2409.16722",
                "title": "LLMs Get a Skeleton Makeover: Fine-Tuning with Less Fuss, More Brains!",
                "institute": "Peking University, Xiaomi",
                "text": "This paper proposes a new fine-tuning method called PMSS (Pre-trained Matrices Skeleton Selection) that leverages the inherent structure of pre-trained weights. Unlike LoRA, which relies on low-rank updates, PMSS enables high-rank updates while maintaining parameter efficiency.",
                "paper-title": "PMSS: Pretrained Matrices Skeleton Selection for LLM Fine-tuning",
                "image-path": "flux_paper_image/2409.16722_1727389440.png"
            },

            {
                "startTime": "14:55",
                "arxivId": "2409.16408",
                "arxivLink": "https://arxiv.org/abs/2409.16408",
                "title": "Hopfield Networks Get a Neural Makeover: Encoding Memories for Better Recall",
                "institute": "IBM",
                "text": "This research introduces Hopfield Encoding Networks (HEN), which integrate encoded neural representations into Modern Hopfield Networks (MHN) to improve pattern separability and reduce meta-stable states. This differs from previous work by specifically addressing the issue of meta-stable states in MHNs through pre-encoding and post-decoding.",
                "paper-title": "Modern Hopfield Networks meet Encoded Neural Representations -- Addressing Practical Considerations",
                "image-path": "flux_paper_image/2409.16408_1727390268.png"
            },

            {
                "startTime": "15:19",
                "arxivId": "2409.16294",
                "arxivLink": "https://arxiv.org/abs/2409.16294",
                "title": "GenCAD: Turning Images into 3D Designs, One Command at a Time!",
                "institute": "MIT",
                "text": "This research introduces GenCAD, a generative model that creates editable 3D shapes from images by generating a sequence of CAD commands. Unlike previous work that focuses on unconditional generation or specific data structures, GenCAD leverages image conditioning to align CAD generation with user intent.",
                "paper-title": "GenCAD: Image-Conditioned Computer-Aided Design Generation with Transformer-Based Contrastive Representation and Diffusion Priors",
                "image-path": "flux_paper_image/2409.16294_1727390370.png"
            },

            {
                "startTime": "15:44",
                "arxivId": "2409.16298",
                "arxivLink": "https://arxiv.org/abs/2409.16298",
                "title": "Antibody Design Gets a Boost from AI's \"BetterBodies\"",
                "institute": "University of Freiburg",
                "text": "This research combines reinforcement learning (RL) with diffusion models to design antibody sequences, a novel approach that allows for optimization of specific properties like binding affinity. Unlike previous work that focuses on generating entire sequences at once, this method takes a stepwise approach, placing amino acids one by one, which allows for better control and potentially improved results.",
                "paper-title": "BetterBodies: Reinforcement Learning guided Diffusion for Antibody Sequence Design",
                "image-path": "flux_paper_image/2409.16298_1727389419.png"
            },

            {
                "startTime": "16:04",
                "arxivId": "2409.16998",
                "arxivLink": "https://arxiv.org/abs/2409.16998",
                "title": "Predicting Surgery Time: A Neural Network Learns the Pituitary Dance!",
                "institute": "University College London",
                "text": "This research introduces PitRSDNet, a neural network model that predicts remaining surgery duration in endoscopic pituitary surgery. Unlike previous models, PitRSDNet incorporates workflow knowledge by predicting surgical steps concurrently with the remaining surgery duration and using prior step predictions as context in temporal learning.",
                "paper-title": "PitRSDNet: Predicting Intra-operative Remaining Surgery Duration in Endoscopic Pituitary Surgery",
                "image-path": "flux_paper_image/2409.16998_1727389059.png"
            },

            {
                "startTime": "16:32",
                "arxivId": "2409.17025",
                "arxivLink": "https://arxiv.org/abs/2409.17025",
                "title": "Robot Surgeons Get a New Training Ground: Pituitary Surgery Simulation Gets Real!",
                "institute": "University College London, NVIDIA, King\u2019s College London...",
                "text": "This research introduces a new public dataset for automated surgical skill assessment in endoscopic pituitary surgery, focusing on a high-fidelity bench-top phantom. This differs from previous work which primarily focused on laparoscopic surgery, isolated tasks, and robotic surgery.",
                "paper-title": "Automated Surgical Skill Assessment in Endoscopic Pituitary Surgery using Real-time Instrument Tracking on a High-fidelity Bench-top Phantom",
                "image-path": "flux_paper_image/2409.17025_1727389739.png"
            },

            {
                "startTime": "16:54",
                "arxivId": "2409.16974",
                "arxivLink": "https://arxiv.org/abs/2409.16974",
                "title": "LLMs: The Good, the Bad, and the Data-Hungry",
                "institute": "San Jose State University, Stanford University",
                "text": "This research provides a systematic overview of the literature on large language models (LLMs), focusing on their development, impacts, and limitations. It goes beyond simply summarizing existing work by conducting a thematic analysis to identify key trends and emerging questions.",
                "paper-title": "Decoding Large-Language Models: A Systematic Overview of Socio-Technical Impacts, Constraints, and Emerging Questions",
                "image-path": "flux_paper_image/2409.16974_1727388626.png"
            },

            {
                "startTime": "17:16",
                "arxivId": "2409.16934",
                "arxivLink": "https://arxiv.org/abs/2409.16934",
                "title": "OCR-Sensitive Neurons: The Secret to Taming Noisy Historical Texts",
                "institute": "\u00c9cole Polytechnique F\u00e9d\u00e9rale de Lausanne",
                "text": "This research investigates the presence of OCR-sensitive neurons within Transformer architectures and their influence on named entity recognition (NER) performance on historical documents. Unlike previous work that focused on improving transcription accuracy or model architecture, this study explores the sensitivity of individual neurons to OCR noise and proposes a method to neutralize these neurons to improve model performance.",
                "paper-title": "Investigating OCR-Sensitive Neurons to Improve Entity Recognition in Historical Documents",
                "image-path": "flux_paper_image/2409.16934_1727389100.png"
            },

            {
                "startTime": "17:35",
                "arxivId": "2409.16710",
                "arxivLink": "https://arxiv.org/abs/2409.16710",
                "title": "Can GPT-4 Sway Experts? A New Turing Test for AI Persuasion",
                "institute": "University of Tokyo",
                "text": "This research goes beyond the traditional Turing test, focusing on how LLM-generated text influences human decisions, particularly in the financial domain. It examines the impact of GPT-4-generated analyses on both amateur and expert investors, analyzing their decision-making processes and the factors that sway their choices.",
                "paper-title": "Beyond Turing Test: Can GPT-4 Sway Experts' Decisions?",
                "image-path": "flux_paper_image/2409.16710_1727388608.png"
            },

            {
                "startTime": "18:00",
                "arxivId": "2409.16469",
                "arxivLink": "https://arxiv.org/abs/2409.16469",
                "title": "Spelling Correction for Speech Recognition: A Lattice-Based Rewrite!",
                "institute": "Google Inc.",
                "text": "This research extends a previous technique for spelling correction in speech recognition to handle non-autoregressive lattices, which are more common in modern systems. The key difference is that the new approach directly converts wordpieces into phonemes, avoiding the need for word representations.",
                "paper-title": "Spelling Correction through Rewriting of Non-Autoregressive ASR Lattices",
                "image-path": "flux_paper_image/2409.16469_1727390246.png"
            },

            {
                "startTime": "18:17",
                "arxivId": "2409.16578",
                "arxivLink": "https://arxiv.org/abs/2409.16578",
                "title": "Robot Brains Get a Tune-Up: Large-Scale Learning Makes Bots Smarter!",
                "institute": "Allen Institute for Artificial Intelligence, University of Texas Austin, University of Washington...",
                "text": "This research proposes FLaRe, a framework for fine-tuning large-scale robot policies using reinforcement learning. Unlike previous work that focused on smaller networks and single-task domains, FLaRe leverages multi-task pre-trained models and large-scale simulations for more robust and generalizable results.",
                "paper-title": "FLaRe: Achieving Masterful and Adaptive Robot Policies with Large-Scale Reinforcement Learning Fine-Tuning",
                "image-path": "flux_paper_image/2409.16578_1727389346.png"
            },

            {
                "startTime": "18:46",
                "arxivId": "2409.16830",
                "arxivLink": "https://arxiv.org/abs/2409.16830",
                "title": "Robot Pathfinding: Learning from Past Mistakes, Offline!",
                "institute": "Indian Institute of Technology Madras, Carnegie Mellon University, Georgia Institute of Technology...",
                "text": "This research proposes an offline reinforcement learning (RL) framework for informative path planning (IPP). Unlike traditional RL approaches that require real-time interaction with the environment, this framework trains an agent using pre-collected datasets generated by arbitrary algorithms.",
                "paper-title": "OffRIPP: Offline RL-based Informative Path Planning",
                "image-path": "flux_paper_image/2409.16830_1727389833.png"
            },

            {
                "startTime": "19:10",
                "arxivId": "2409.16860",
                "arxivLink": "https://arxiv.org/abs/2409.16860",
                "title": "AI Doctors: Can Language Models Heal Healthcare?",
                "institute": "CHRISTUS SantaRosa Hospital, Riphah International University, Palo Alto CA",
                "text": "This research provides a comprehensive review of the use of large language models (LLMs) in healthcare, focusing on their strengths, challenges, and ethical considerations. It distinguishes itself from previous work by offering a detailed exploration of the various applications of LLMs in healthcare, including medical diagnostics, patient care, and drug discovery.",
                "paper-title": "The Role of Language Models in Modern Healthcare: A Comprehensive Review",
                "image-path": "flux_paper_image/2409.16860_1727388708.png"
            },

            {
                "startTime": "19:31",
                "arxivId": "2409.16770",
                "arxivLink": "https://arxiv.org/abs/2409.16770",
                "title": "Sewage Surveillance Gets a Smart Upgrade: Evolutionary Algorithm Finds the Best Sensor Spots!",
                "institute": "University of Hong Kong, National University of Singapore, University College London",
                "text": "This research introduces an Evolutionary Greedy (EG) algorithm for optimal sensor placement in sewage surveillance networks. Unlike previous greedy algorithms that focus on single-objective optimization, EG tackles multi-objective optimization by incorporating an evolutionary mechanism to generate and evaluate a diverse set of solutions.",
                "paper-title": "Evolutionary Greedy Algorithm for Optimal Sensor Placement Problem in Urban Sewage Surveillance",
                "image-path": "flux_paper_image/2409.16770_1727389042.png"
            },

            {
                "startTime": "19:52",
                "arxivId": "2409.16973",
                "arxivLink": "https://arxiv.org/abs/2409.16973",
                "title": "LLMs Get Personal: Self-Supervised Learning Makes AI More User-Friendly",
                "institute": "University of Toronto, National University of Singapore, University of Oxford...",
                "text": "This research introduces Adaptive Self-Supervised Learning Strategies (ASLS) for on-device LLM personalization. Unlike traditional methods that rely heavily on labeled datasets, ASLS utilizes self-supervised learning techniques to dynamically adapt LLMs to individual user preferences without requiring extensive labeled data.",
                "paper-title": "Adaptive Self-Supervised Learning Strategies for Dynamic On-Device LLM Personalization",
                "image-path": "flux_paper_image/2409.16973_1727389271.png"
            },

            {
                "startTime": "20:19",
                "arxivId": "2409.16843",
                "arxivLink": "https://arxiv.org/abs/2409.16843",
                "title": "Time Travel for Forecasts: Finding the Perfect Starting Point for Accurate Predictions",
                "institute": "Central University of Finance and Economics, Chinese Academy of Sciences, Peking University...",
                "text": "This research focuses on optimizing the starting point of time series data for forecasting, rather than just improving the forecasting models themselves. It proposes a novel approach called OSP-TSP (Optimal Starting Point Time Series Forecast) that uses machine learning to identify the best starting point for a time series, leading to more accurate predictions.",
                "paper-title": "Optimal starting point for time series forecasting",
                "image-path": "flux_paper_image/2409.16843_1727390163.png"
            },

            {
                "startTime": "20:46",
                "arxivId": "2409.16399",
                "arxivLink": "https://arxiv.org/abs/2409.16399",
                "title": "ASR's New Ears: Bio-Inspired Features for Robust Speech Recognition",
                "institute": "CMU",
                "text": "This research explores the impact of using acoustic features inspired by human auditory perception on the accuracy and robustness of Automatic Speech Recognition (ASR) systems. Unlike previous work that focused on improving ASR models through complex neural networks and large datasets, this study investigates the potential of biologically plausible features to enhance robustness, particularly against adversarial attacks.",
                "paper-title": "Revisiting Acoustic Features for Robust ASR",
                "image-path": "flux_paper_image/2409.16399_1727389035.png"
            },

            {
                "startTime": "21:13",
                "arxivId": "2409.16495",
                "arxivLink": "https://arxiv.org/abs/2409.16495",
                "title": "FL Goes Hierarchical: Flight Takes Federated Learning to New Heights!",
                "institute": "University of Chicago, Argonne National Laboratory",
                "text": "This research introduces Flight, a federated learning framework that supports complex hierarchical multi-tier topologies, unlike existing frameworks that typically assume simple two-tier structures.",
                "paper-title": "Flight: A FaaS-Based Framework for Complex and Hierarchical Federated Learning",
                "image-path": "flux_paper_image/2409.16495_1727389449.png"
            },

            {
                "startTime": "21:31",
                "arxivId": "2409.16336",
                "arxivLink": "https://arxiv.org/abs/2409.16336",
                "title": "Refereeing the Referees: New Tests for Generative Models in High Dimensions",
                "institute": "University of Genova, INFN, MaLGa-DIBRIS",
                "text": "This research introduces a novel sliced Kolmogorov-Smirnov statistic for evaluating generative models, comparing its performance to existing metrics like the sliced Wasserstein distance and Maximum Mean Discrepancy.",
                "paper-title": "Refereeing the Referees: Evaluating Two-Sample Tests for Validating Generators in Precision Sciences",
                "image-path": "flux_paper_image/2409.16336_1727388898.png"
            },

            {
                "startTime": "21:54",
                "arxivId": "2409.16380",
                "arxivLink": "https://arxiv.org/abs/2409.16380",
                "title": "Forest Fires? Deep Learning to the Rescue!",
                "institute": "University of West Florida, Florida Insitute for Human and Machine Cognition (IHMC), Google",
                "text": "This research builds a large, labeled dataset of satellite images specifically for wildfire detection using deep learning. Previous studies have used smaller datasets or focused on different types of forest disturbances.",
                "paper-title": "Development and Application of a Sentinel-2 Satellite Imagery Dataset for Deep-Learning Driven Forest Wildfire Detection",
                "image-path": "flux_paper_image/2409.16380_1727389684.png"
            },

            {
                "startTime": "22:14",
                "arxivId": "2409.17054",
                "arxivLink": "https://arxiv.org/abs/2409.17054",
                "title": "AI Doctor's Notes: Whisper & GPT-3 Team Up to Streamline Indonesian Healthcare",
                "institute": "Stanford University",
                "text": "This research focuses on using a localized large language model (LLM) to transcribe and summarize doctor-patient conversations in Bahasa Indonesia, specifically for the ePuskesmas system. This differs from previous work by focusing on a specific language and healthcare system, aiming to improve efficiency and accuracy of medical records.",
                "paper-title": "Using LLM for Real-Time Transcription and Summarization of Doctor-Patient Interactions into ePuskesmas in Indonesia",
                "image-path": "flux_paper_image/2409.17054_1727388880.png"
            },

            {
                "startTime": "22:35",
                "arxivId": "2409.16327",
                "arxivLink": "https://arxiv.org/abs/2409.16327",
                "title": "GATher: Gene-Disease Links, Predicted with a Graph's Attention Span!",
                "institute": "Exscientia, University of Dundee",
                "text": "This research introduces a new graph attention network called GATv3, which incorporates a context-aware attention mechanism to better capture the complex interactions within biomedical graphs. This differs from previous work by considering shared interactors among biological nodes, identifying nodes that are similar if linked to common diseases, functions, or interactors.",
                "paper-title": "GATher: Graph Attention Based Predictions of Gene-Disease Links",
                "image-path": "flux_paper_image/2409.16327_1727388935.png"
            },

            {
                "startTime": "22:58",
                "arxivId": "2409.16900",
                "arxivLink": "https://arxiv.org/abs/2409.16900",
                "title": "LLMs Need a Body, a Brain, and a Social Life: Grounding AI in Reality",
                "institute": "Italian Institute of Technology",
                "text": "This research proposes a roadmap for grounding LLMs in the real world, emphasizing the importance of embodiment, temporally structured experience, and social interaction, going beyond simply connecting LLMs to robots.",
                "paper-title": "A Roadmap for Embodied and Social Grounding in LLMs",
                "image-path": "flux_paper_image/2409.16900_1727388560.png"
            },

            {
                "startTime": "23:19",
                "arxivId": "2409.16872",
                "arxivLink": "https://arxiv.org/abs/2409.16872",
                "title": "AI Ethics: A Framework for Keeping Robots in Line!",
                "institute": "University College London",
                "text": "This research proposes a unified framework that integrates ethical AI governance with legal compliance, addressing the scalability of AI systems in diverse business contexts. This framework differs from previous work by explicitly addressing the interplay between ethical principles and legal requirements in the context of scalable AI automation.",
                "paper-title": "Ethical and Scalable Automation: A Governance and Compliance Framework for Business Applications",
                "image-path": "flux_paper_image/2409.16872_1727389850.png"
            },

            {
                "startTime": "23:37",
                "arxivId": "2409.16422",
                "arxivLink": "https://arxiv.org/abs/2409.16422",
                "title": "Learning's Secret Sauce: All About Natural Gradient Descent",
                "institute": "MIT, IBM Research",
                "text": "This paper demonstrates that a wide class of effective learning rules, those that improve a scalar performance measure over time, can be rewritten as natural gradient descent with respect to a suitably defined loss function and metric. This is a significant departure from previous work, which often focused on specific learning rules or assumed monotonic improvement in the performance measure.",
                "paper-title": "Is All Learning (Natural) Gradient Descent?",
                "image-path": "flux_paper_image/2409.16422_1727390358.png"
            },

            {
                "startTime": "23:56",
                "arxivId": "2409.16779",
                "arxivLink": "https://arxiv.org/abs/2409.16779",
                "title": "LLaMa-SciQ: The Chatbot That Makes Science MCQs a Breeze!",
                "institute": "\u00c9cole Polytechnique F\u00e9d\u00e9rale de Lausanne",
                "text": "This research focuses on fine-tuning a large language model (LLM) specifically for answering science multiple-choice questions (MCQs). The novelty lies in the use of specialized datasets for training and alignment with human preferences, particularly in STEM fields.",
                "paper-title": "LLaMa-SciQ: An Educational Chatbot for Answering Science MCQ",
                "image-path": "flux_paper_image/2409.16779_1727389009.png"
            },

            {
                "startTime": "24:12",
                "arxivId": "2409.16430",
                "arxivLink": "https://arxiv.org/abs/2409.16430",
                "title": "LLMs: Not Just Smart, But Fair? A Survey of Bias in Language Models",
                "institute": "Carnegie Mellon University, BIT Sindri",
                "text": "This research provides a comprehensive survey of bias in LLMs, going beyond previous work by systematically categorizing bias types, sources, impacts, and mitigation strategies. It also critically assesses existing bias mitigation techniques and proposes future research directions to enhance fairness and equity in LLMs.",
                "paper-title": "A Comprehensive Survey of Bias in LLMs: Current Landscape and Future Directions",
                "image-path": "flux_paper_image/2409.16430_1727389461.png"
            },

            {
                "startTime": "24:36",
                "arxivId": "2409.17049",
                "arxivLink": "https://arxiv.org/abs/2409.17049",
                "title": "ControlCity: Building Footprints with a Multimodal Twist!",
                "institute": "Zhejiang Agriculture and Forestry University, Xiaohongshu, Zhejiang University",
                "text": "This research introduces ControlCity, a multimodal diffusion model that generates urban building footprints using OpenStreetMap data. Unlike previous methods that rely solely on road networks, ControlCity integrates image, text, and metadata inputs, leading to more accurate and detailed results.",
                "paper-title": "ControlCity: A Multimodal Diffusion Model Based Approach for Accurate Geospatial Data Generation and Urban Morphology Analysis",
                "image-path": "flux_paper_image/2409.17049_1727390390.png"
            },

            {
                "startTime": "25:04",
                "arxivId": "2409.17141",
                "arxivLink": "https://arxiv.org/abs/2409.17141",
                "title": "FineZip: LLMs Get a Speed Boost for Text Compression!",
                "institute": "UC Berkeley",
                "text": "This research introduces FineZip, a new text compression system that combines online memorization and dynamic context to significantly reduce compression time compared to previous LLM-based methods.",
                "paper-title": "FineZip : Pushing the Limits of Large Language Models for Practical Lossless Text Compression",
                "image-path": "flux_paper_image/2409.17141_1727389824.png"
            },

            {
                "startTime": "25:24",
                "arxivId": "2409.16849",
                "arxivLink": "https://arxiv.org/abs/2409.16849",
                "title": "AI Benchmarks: Unmasking the Hidden Assumptions!",
                "institute": "University of Oxford, Aarhus University",
                "text": "This research proposes using explicit cognitive models, operationalized through Structural Equation Modeling (SEM), to expose assumptions in how test batteries relate to theoretical constructs. This approach differs from previous work that primarily focused on applying human-oriented psychometric batteries to generative models.",
                "paper-title": "Exposing Assumptions in AI Benchmarks through Cognitive Modelling",
                "image-path": "flux_paper_image/2409.16849_1727390239.png"
            }
    ],
    "stats": {
        "num_pick": 64,
        "num_total": 327,
    },
    "audio": "https://d2irtorupa9e8g.cloudfront.net/daily_podcast/202409261549_audio.mp3"
}